//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductPrice { get; set; }
        public Nullable<int> QuantityAvailable { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ImagePath { get; set; }
        public string AlternateText { get; set; }
        public string UserName { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
